a = int(input("Digite o valor da variável A: "))
b = int(input("Digite o valor da variável B: "))
c = int(input("Digite o valor da variável C: "))
d = int(input("Digite o valor da variável D: "))
print("O resultado da soma de A e B:",a+b)
print("O resultado da soma de C e A:",a+c)
print("O resultado da soma de A e D:",a+d)
print("O resultado da soma de B e C:",b+c)
print("O resultado da soma de B e D:",b+d)
print("O resultado da soma de C e D:",c+d)
print("O resultado da multiplicação de B e A:",a*b)
print("O resultado da multiplicação de C e A:", a*c)
print("O resultado da multiplicação de A e D:",a*d)
print("O resultado da multiplicação de B e C:",b*c)
print("O resultado da multiplicação de B e D:",b*d)
print("O resultado da multiplicação de C e D:",c*d)

